import { Hono } from 'hono';
import { zValidator } from '@hono/zod-validator';
import { emptyQuerySchema } from '@/schemas/common.schema';

export const createUtilRoutes = () => {
  const util = new Hono()

  /**
   * GET /api/utils/document-types
   * Returns list of document types that students can upload
   * Excludes SURAT_PENGANTAR (which is auto-generated by admin)
   */
    .get('/document-types', zValidator('query', emptyQuerySchema), (c) => {
      const uploadableDocumentTypes = [
        'PROPOSAL_KETUA',
        'SURAT_KESEDIAAN',
        'FORM_PERMOHONAN',
        'KRS_SEMESTER_4',
        'DAFTAR_KUMPULAN_NILAI',
        'BUKTI_PEMBAYARAN_UKT',
        // ❌ SURAT_PENGANTAR is intentionally excluded - auto-generated only
      ];

      return c.json({
        success: true,
        message: 'Document types retrieved',
        data: uploadableDocumentTypes,
      });
    })

  /**
   * GET /api/utils/document-types/all
   * Returns ALL document types including SURAT_PENGANTAR
   * For admin/system use only
   */
    .get('/document-types/all', zValidator('query', emptyQuerySchema), (c) => {
      const allDocumentTypes = [
        'PROPOSAL_KETUA',
        'SURAT_KESEDIAAN',
        'FORM_PERMOHONAN',
        'KRS_SEMESTER_4',
        'DAFTAR_KUMPULAN_NILAI',
        'BUKTI_PEMBAYARAN_UKT',
        'SURAT_PENGANTAR', // ✅ Included for completeness
      ];

      return c.json({
        success: true,
        message: 'All document types retrieved',
        data: allDocumentTypes,
      });
    });

  return util;
};
