#!/usr/bin/env sh
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

bun run typecheck
if [ $? -ne 0 ]; then
    echo "TypeScript check failed. Please fix the errors before pushing."
    exit 1
fi
